export declare class Clock {
    private root;
    private Id?;
    private Class?;
    private Style?;
    private node;
    private interval;
    private timer;
    private sec;
    private min;
    private ore;
    private secs;
    private CountDown;
    private tick;
    private endtime;
    private started;
    private stopped;
    endtime$: import("rxjs").Observable<any>;
    started$: import("rxjs").Observable<any>;
    stopped$: import("rxjs").Observable<any>;
    tick$: import("rxjs").Observable<any>;
    time: string;
    constructor(root: HTMLElement, Id?: string, Class?: string, Style?: string);
    Init: () => void;
    start: () => void;
    stop: () => void;
    setCountDown: (ore: number, minuti: number, secondi: number) => void;
    private setClock;
    private secToTimeFormat;
}
